name: "Hello Actions"
description: "Greet Anacondong"
author: "westkitseo@github.com"

inputs:
  MY_NAME:
    description: "Who to greet from worklows (config param)"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
