apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: springboot-api
  template:
    metadata:
      labels:
        app: springboot-api
    spec:
      containers:
        - name: springboot-api
          image: anacondong/springboot:latest
          ports:
            - containerPort: 8080  # Assuming your Spring Boot app runs on port 8080
