apiVersion: v1
kind: Service
metadata:
  name: springboot-api-service
spec:
  selector:
    app: springboot-api  # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Assuming your Spring Boot app runs on port 8080
  type: NodePort
